name: GitHub Actions Demo

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create file
        run: echo "Bonjour depuis GitHub Actions" > fichier.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: mon-fichier
          path: fichier.txt